# -*- coding: utf-8 -*-
"""Essential Pyphon for DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-vCglGELyMieG68Qemyact3L67-fUH2

# Essential Pyphon for DA

- Object Oriented Programming
- Read and Write file
- Context Manager
- Handle Error
- Pandas & Numpy (on demand)
- Request API

#**OOP**
"""

class Dog:
    def __init__(self, name, species, age):
        self.name = name
        self.species = species
        self.age = age
    def bark(self):
        print(f"{self.name} is barking woof woof")
    def hbd(self):
        self.age += 1 #self.age = self.age + 1

## Atributes
dog1 = Dog("Milo", "pugs", 3)
dog2 = Dog("David", "Husky", 4)

print(f"{dog1.name} is {dog1.species}")

dog1.bark()

print(dog1.age)
dog1.hbd()
print(dog1.age)



"""## OOP
* attributes: name, species, age
* methods: function bark(), hbd()
"""



"""# Homework"""

class ATM:
    pass

class ATM:
    def __init__(self, userName, bank, amount):
        self.userName = userName
        self.bank = bank
        self.amount = amount


    def check_balance(self):
        print(f"balance is {self.amount}")

    def deposit(self, saving):
        self.amount += saving
        print(f"Deposit {saving} is successfully!")

    ## special function string method that use with print!
    def __str__(self):
        return "This is my bank acc!"

kaew = ATM("orawan kaew", "UOB", 100)

print(f"{kaew.userName} opens a new bank account at {kaew.bank} THB")

kaew.check_balance()

kaew.deposit(200)

kaew.check_balance()

print(kaew)



"""# Concept Super class
extend feature from base class

"""

## Base class
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

## super class
class Employee(Person):
    def __init__(self, name, age, company):
        super().__init__(name, age)
        self.company = company

## new method
    def greeting(self):
        print("Hello World")

person1 = Person("kaew", 38)

person2 = Employee("lisa", 28, "KR")

person1.greeting()

person2.greeting()



"""# Try Except Block
วิธีจับ bug
"""

try:
    result = 1/0
except:
    print("This is an error message!")



"""# Read and write files"""

## write file + context manager
import csv
head = ["id", "name", "city"]
body = [
    [1,"CU", "BKK"],
    [2, "LSE", "London"],
    [3, "Reading", "Reading"]
]

with open("school.csv", "w") as file: #using write mode "w"
    writer = csv.writer(file)
    writer.writerow(head) # writerow() เขียนที่ละแถว
    writer.writerows(body) # writerows() เขียนหลายแถว

!ls

!cat school.csv

## modern Python
import pandas as pd

df = pd.read_csv("school.csv")

df.head()

## export csv file in pandas
df.to_csv("school2.csv")

!cat school2.csv



"""# Read data from internet"""

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

## import pandas as pd
import pandas as pd
df_penguin = pd.read_csv(url)

## show header default 5 rows
df_penguin.head()

## show tail default 5 rows
df_penguin.tail()

## select column
df_penguin[["species", "island", "body_mass_g"]].head(10) ## select 3 columns and show top 10 rows

## filter rows
df_penguin[["species", "island", "body_mass_g"]].query("species == 'Adelie' and island == 'Dream'")

df_penguin[["species", "island", "body_mass_g"]]\
		.query("species == 'Adelie' and island == 'Dream'")\
		.head(10)

# filter without query
df_penguin[df_penguin['body_mass_g'] >= 4500] [["species", "sex", "body_mass_g"]]

## requests

"""# Requests
How to get data via API the easy way
"""

import requests

## go to API star war via url
## step 1: go to website [https://swapi.info/]
## step 2: copy url u need
import requests
url = "https://swapi.info/api/people/1" ## need information people #1 from api endpoint

response = requests.get(url)

response.json()

response.json()["name"]

## ดึง data frame 10 peoples
## for loop
import requests
import time

names = []
for i in range(3):
    url = f"https://swapi.info/api/people/{i+1}" ## index in Python start with 0 then need to +1 to start from people #1
    response = requests.get(url)
    response_json = response.json()
    names.append(response_json["name"])
    print(f"Success: {i+1}")
    time.sleep(1) ## break 1 sec before pull next data index

print(names)

## for loop example #3
import requests
import time

characters = []
for i in range(3):
    url = f"https://swapi.info/api/people/{i+1}" ## index in Python start with 0 then need to +1 to start from people #1
    response = requests.get(url)
    response_json = response.json()
    data = [response_json["name"],
    response_json["height"],
    response_json["mass"]]
    characters.append(data)
    print(f"Success: {i+1}")
    time.sleep(1) ## break 1 sec before pull next data index

print(characters)

## pd dataframe create from list
import pandas as pd
starwars = pd.DataFrame(characters, columns = ["name", "height", "mass"])

starwars

